import images from '../image';
import img from '../category/image';

export default {
  user: {
    favorites: [],
    lastSeen: [],
    role: '',
    _id: '',
    name: '',
    surname: '',
    email: '',
    password: '',
    phone: '',
    address: {
      _id: '',
      country: '',
      city: '',
      place: '',
      street: '',
      block: '',
      building: '',
      flat: '',
      zip: '',
    },
  },
  auth: {
    accces_token: '',
  },
  products: [
    {
      images: [],
      totalQuantity: '',
      _id: '',
      name: '',
      category: '',
      price: '',
      description: '',
    },
  ],
  orders: [
    {
      _id: '',
      products: [
        {
          _id: '',
          images: [],
          totalQuantity: '',
          name: '',
          category: '',
          price: '',
          description: '',
        },
      ],
    },
  ],
  categories: [],
  localCategories: [
    {
      name: 'Крупная бытовая техника',
      image: images.catalogImages.img1,
      titleId: 'kbtTitle',
      catList_id: 'kbtList',
      spanId: 'titleIcon1',
      items: [
        {
          name: 'Холодильники',
          category: 'refrigerators',
          images: img.kbt.xol1,
          products: [],
        },
        {
          name: 'Посудомоечные машины',
          category: 'dishwashers',
          images: img.kbt.xol2,
          products: [],
        },
        {
          name: 'Кухонные плиты',
          category: 'сookers',
          images: img.kbt.xol3,
          products: [],
        },
        {
          name: 'Морозильные камеры',
          category: 'freezers',
          images: img.kbt.xol4,
          products: [],
        },
        {
          name: 'Стиральные машины',
          category: 'Стиральные машины',
          images: img.kbt.xol5,
          products: [],
        },
        {
          name: 'Сушильные машины',
          category: 'drying_machines',
          images: img.kbt.xol6,
          products: [],
        },
      ],
    },
    {
      name: 'Встраиваемая техника',
      image: images.catalogImages.img2,
      titleId: 'itTitle',
      catList_id: 'itList',
      spanId: 'titleIcon2',
      items: [
        {
          name: 'Встраиваемые духовые шкафы',
          category: 'built_in_ovens',
          images: img.it.itImg1,
          products: [],
        },
        {
          name: 'Посудомоечные машины',
          category: 'dishwashers',
          images: img.it.itImg2,
          products: [],
        },
        {
          name: 'Встраиваемые варочные поверхности',
          category: 'built_in_hobs',
          images: img.it.itImg3,
          products: [],
        },
        {
          name: 'Кухонные вытяжки',
          category: 'cooker_hoods',
          images: img.it.itImg4,
          products: [],
        },
        {
          name: 'Измельчители пищевых отходов',
          category: 'food_waste_disposers',
          images: img.it.itImg5,
          products: [],
        },
        {
          name: 'Аксессуары к вбт',
          category: 'Accessories_for_vbt',
          images: img.it.itImg6,
          products: [],
        },
      ],
    },
    {
      name: 'Уход за домом и одеждой',
      image: images.catalogImages.img3,
      titleId: 'homeTitle',
      catList_id: 'homeList',
      spanId: 'titleIcon3',
      items: [
        {
          name: 'Кофемашины',
          category: 'coffee_machines',
          images: img.home.homeImg1,
          products: [],
        },
        {
          name: 'Мультиварки',
          category: 'multicooker',
          images: img.home.homeImg2,
          products: [],
        },
        {
          name: 'Печи СВЧ',
          category: 'microwave_ovens',
          images: img.home.homeImg3,
          products: [],
        },
        {
          name: 'Блендеры',
          category: 'blenders',
          images: img.home.homeImg4,
          products: [],
        },
        {
          name: 'Грили',
          category: 'grills',
          images: img.home.homeImg5,
          products: [],
        },
        {
          name: 'Аксессуары для кухонной техники',
          category: 'accessories_for_kitchen_appliances',
          images: img.home.homeImg6,
          products: [],
        },
        {
          name: 'Прочая мелкая техника',
          category: 'other_small_equipment',
          images: img.home.homeImg7,
          products: [],
        },
      ],
    },
    {
      name: 'Техника для кухний',
      image: images.catalogImages.img4,
      titleId: 'inTitle',
      catList_id: 'inList',
      spanId: 'titleIcon4',
      items: [
        {
          name: 'Пылесосы',
          category: 'vacuum_cleaners',
          images: img.kitchen.kitchenImg1,
          products: [],
        },
        {
          name: 'Роботы-пылесосы',
          category: 'robot_vacuum_cleaners',
          images: img.kitchen.kitchenImg2,
          products: [],
        },
        {
          name: 'Утюги',
          category: 'irons',
          images: img.kitchen.kitchenImg3,
          products: [],
        },
        {
          name: 'Швейная техника и аксессуары',
          category: 'sewing_equipment_and_accessories',
          images: img.kitchen.kitchenImg4,
          products: [],
        },
        {
          name: 'Пароочистители',
          category: 'steam_cleaners',
          images: img.kitchen.kitchenImg5,
          products: [],
        },
        {
          name: 'Аксессуары к товарам по уходу за домом и одеждой',
          category: 'accessories_for_home_care_and_clothing_products',
          images: img.kitchen.kitchenImg6,
          products: [],
        },
      ],
    },
  ],
  cart: [],
};
