export default {
  headerModalWrap: document.querySelector('.header-modal'),
  headerWrap: document.querySelector('.header'),
  mobileNav: document.querySelector('#mobileNav'),
  burgerBtn: document.querySelector('#burgerBtn'),
  logo: document.querySelector('.js-logo'),
  phoneTrigger: document.querySelector('.js-phone'),
  searchHeader: document.querySelector('.js-search'),
  searachModal: document.querySelector('#search-modal'),
  cart: document.querySelector('.js-cart'),
  modalBtn: document.querySelector('.js-burger'),
  openModal: document.querySelector('.icon-burger'),
  closeModal: document.querySelector('.header-modal-close-btn'),
  catalog: document.querySelector('.catalog'),
  catalogBtn: document.querySelector('.js-catalog'),
  catBtnIcon: document.getElementById('catBtnIcon'),
  sale: document.querySelector('.js-sale'),
  information: document.querySelector('.js-info'),
  account: document.querySelector('.js-profile'),
  likes: document.querySelector('.js-likes'),
  modalHeader: document.querySelector('.modal'),
  modalWrapper: document.querySelector('.modal-wrapper'),
  modalBackdrop: document.querySelector('.backdrop'),
  modalList: document.querySelector('.modal-list')
};